theme: jekyll-theme-minimal
title: Dr. Fangni Zhang
description: Assistant Professor
description: Department of Industrial and Manufacturing Systems Engineering
description: The University of Hong Kong
